# Generated by Django 4.2.1 on 2023-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=500)),
                ('expiry', models.DateField(null=True)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
            ],
        ),
    ]
